apiVersion: v1
kind: ConfigMap
metadata:
	name: first-chart-configmap-{{.Chart.Version}}
data:
	port: "8080"
	{{if eq .Value.env "staging"}}
		allowTesting: "true"
	{{else}}
		allowTesting: "false"
	{{end}}